name: on_push

on:
  push:
    branch:
      - "**"


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      HEADLESS_CHROME: true
    steps:
      - name: Run Tests With Mavan
        run: echo "START_TIME=$(date+%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Run Tests With Mavan
        run: mvn test
      - name: Collect Build Data
        if: always()
        run: expr $(date+%s) - ${START_TIME}
